name: Build

on:
  workflow_call

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps chromium

      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
