StylesPath = .vale
MinAlertLevel = suggestion
Vocab = Android, CMake, Dotnet, General, Windows

# Treat MDX files as Markdown
[formats]
mdx = md

[*.{md,mdx}]
BasedOnStyles = Vale
BlockIgnores = (`{3}.*`{3}), (-{3}.*-{3})
TokenIgnores = (`[^`]+`)
