StylesPath = .vale
MinAlertLevel = suggestion
Vocab = AI, Android, AOC, Backpacking, Blog, CMake, Dotnet, General, GoogleHome, Kotlin, Languages, Markdown, Miscellaneous, Names, Typescript, Windows
IgnoredScopes = code, tt, kbd, text.frontmatter

# Treat MDX files as Markdown
[formats]
mdx = md

[*.{md,mdx}]
BasedOnStyles = Vale
TokenIgnores = (?!\[.*])\(.*\),(<\/?Char>),(github\.com\/.*),(\_)
