title: Bart Kessels
subtitle: Passionate open source developer
url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: Blog
      url: /blog

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: authors/bartkessels.png
author: Bart Kessels
author_bio: Passionate open source developer
author_email: "development@bk-mail.com"
author_website_url: "https://bartkessels.net"
typewrite-text: I'm a passionate open source developer

# Experiences
author_work_experiences:
            - company_name: RazorBit
              years: 2015 - Present
              company_url: https://razorbit.nl
              designation: Founder & Software engineer
              description: Building (web) API's and Android/Flutter apps
              visibility: true
            - company_name: Newway
              years: 2018 - 2019
              company_url: https://newway.nl
              designation: (Internship) Software engineer
              description: Developing an abstraction for connection multiple ATM's to their POS application
              visibility: true
            - company_name: Skindustries
              years: 2016
              company_url: https://skindustries.nl
              designation: (Internship) Mobile application developer
              description: With two other interns we built a inhouse social network for connecting their co-workers and interns
              visibility: true

# Education
author_education_details:
              - college_name: HAN
                college_url: https://han.nl
                college_degree: CS Engineer
                description: Bachelor of technology with a minor in Mobile Application Development
                visibility: true

# Open source projects
author_open_source_projects:
              - project_thumbnail: projects/getit.png
                project_title: GetIt
                project_description: GetIt is a simple to use open source HTTP client
                project_url: https://getit.bartkessels.net
                github_url: https://github.com/bartkessels/getit
                platforms:
                  - title: Download GetIt from Fedora COPR
                    icon: fab fa-fedora
                    url: https://copr.fedorainfracloud.org/coprs/bartkessels/getit/
                  - title: Download GetIt as a flatpak from Flathub
                    icon: fas fa-cubes
                    url: https://flathub.org/apps/details/net.bartkessels.getit
                visibility: true
              - project_thumbnail: projects/backing.png
                project_title: Backing
                project_description: >-
                  Simply setup a uri and you're able to mock multiple HTTP methods.
                  For each mocked method you're able to set the status code, headers and ofcourse the body.
                  All requests will be logged to the output at the bottom of the screen so you can easily 
                  detect if your front-end is sending data to the expected back-end.
                project_url: https://backing.bartkessels.net
                github_url: https://github.com/bartkessels/backing
                visibility: true
              - project_thumbnail: projects/advancedmetronome.png
                project_title: Advanced Metronome
                project_description: >-
                  Advanced Metronome is a small application in which you can set multiple measures with their own 
                  speed, time-signature and number of repeats. This gives you the ability to practice songs that 
                  have multiple speeds and/or time-signatures.
                project_url: https://github.com/bartkessels/advancedmetronome
                github_url: https://github.com/bartkessels/advancedmetronome
                platforms:
                    - title: Download Advanced Metronome from Fedora COPR
                      icon: fab fa-fedora
                      url: https://copr.fedorainfracloud.org/coprs/bartkessels/advancedmetronome/
                    - title: Download Advanced Metronome for Windows
                      icon: fab fa-windows
                      url: https://github.com/bartkessels/AdvancedMetronome/releases/latest/download/AdvancedMetronomeInstaller.exe
                visibility: true
              - project_thumbnail: projects/hashgenerator.png
                project_title: Hash Generator
                project_description: >-
                  Hash Generator is a small application to generate multiple hashes from any input string you give it.
                  The code is designed to easily add new hashing algorithms so if you're missing anything feel free 
                  to open a pull-request or create an issue.
                project_url: https://github.com/bartkessels/hashgenerator
                github_url: https://github.com/bartkessels/hashgenerator
                platforms:
                  - title: Download Hash Generator for MacOS
                    icon: fab fa-apple
                    url: https://github.com/bartkessels/HashGenerator/releases/latest/download/hashgen_macos_x64.dmg
                  - title: Download Hash Generator for Windows
                    icon: fab fa-windows
                    url: https://github.com/bartkessels/HashGenerator/releases/latest/download/hashgen_win_x64.exe
                visibility: true

author_proprietary_projects:
              - project_thumbnail: projects/wocoapp.png
                project_title: WocoAPP
                project_involvement: Built the API & Flutter/Android application
                project_description: >-
                  The WocoAPP is an application which gives tenants a more easy way of contacting their housing
                  corporations. This can be as simple as a contact form, or even a complete repair request with
                  pictures of the problem. When a tenant has sent a message or repeair request, the corporation can
                  live-chat with that particular tent
                project_url: https://wocoapp.nl
                platforms:
                  - title: Download WocoAPP from the Google Play Store
                    icon: fab fa-google-play
                    url: https://play.google.com/store/apps/details?id=nl.razorbit.wocoapp
                  - title: Download WocoAPP from the Apple App Store
                    icon: fab fa-apple
                    url: https://itunes.apple.com/nl/app/wocoapp/id1375323603?mt=8
                visibility: true
              - project_thumbnail: projects/constructifapp.jpg
                project_title: Constructif | Bewoners
                project_involvement: Built the API & Flutter/Android application
                project_description: >-
                  The ConstructifAPP is used by Constructif to keep their tenants up-to-date on
                  all development/renovations around their own house.
                project_url: https://constructifapp.nl
                platforms:
                  - title: Download ConstructifAPP from the Google Play Store
                    icon: fab fa-google-play
                    url: https://play.google.com/store/apps/details?id=nl.razorbit.constructifapp
                  - title: Download ConstructifAPP from the Apple App Store
                    icon: fab fa-apple
                    url: https://apps.apple.com/gb/app/constructif-bewoners/id1481123214
                visibility: true

# social links
twitter_username: _bartkessels
github_username:  bartkessels
linkedin_username: kesselsbart

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
