# Site
name: "Bart Kessels"
title: "Bart Kessels"
description: "Passionate open source software engineer."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'UA-46278016-1'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  bart:
    name: Bart Kessels
    display_name: Bart Kessels
    avatar: assets/images/bartkessels.png
    email: development@bk-mail.com
    web: https://bartkessels.net
    twitter: https://github.com/bartkessels
    description: "Passionate open source software engineer who loves to go backpacking"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
