# Site settings
title: Bart Kessels
description: 'Software developer from the Netherlands'
url: 'https://bartkessels.net'
baseurl: '/'

author:
  name: 'Bart Kessels'
  email: bartkessels@outlook.com
  github_username:  bartkessels
  linkedin_username:  kesselsbart
  youtube_username: bartkessels

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: true

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
