name: Validate website

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/steps/lint.yml

  check-content:
    uses: ./.github/workflows/steps/check-content.yml

  test:
    uses: ./.github/workflows/steps/test.yml

  test-e2e:
    uses: ./.github/workflows/steps/test-e2e.yml
